### ISSUE TITLE
Firefox desktop action entries not launching

### ISSUE THREAD

**Issue by NullSense** [Biont/sway-launcher-desktop#21] opened 2020-04-17 10:05 UTC
E.g. [Desktop Action new-private-window] (file can be found in /usr/share/applications/firefox.desktop) does not launch with the current implementation, I tried adding new Desktop actions for launching my custom firefox profiles, but they also seem to not work.

**Comment by Biont** [comment] 2020-04-17 20:57
Thanks for the report. I'm seeing the same, so I shall have a look

**Comment by Biont** [comment] 2020-04-18 19:35
Got the wrong issue id in the smart commit, but I believe this is now fixed in 7cc736d5d37f33c6b07eea15c9d220dd2ee5b7c9 @NullSense Can you please check?

I hope this does not break anything, but it really looks like a regression from an erlier state of the script: The last character of the desktop action was stripped so it could then no longer be found.

If that's the case, the entire feature must have been broken for a while now ...

**Comment by NullSense** [comment] 2020-04-20 08:47
That seemed to have fixed it. Thanks @Biont

**Closed** 2020-04-20 09:01 UTC
Labels: bug
